module.exports = (function() {
var __MODS__ = {};
var __DEFINE__ = function(modId, func, req) { var m = { exports: {}, _tempexports: {} }; __MODS__[modId] = { status: 0, func: func, req: req, m: m }; };
var __REQUIRE__ = function(modId, source) { if(!__MODS__[modId]) return require(source); if(!__MODS__[modId].status) { var m = __MODS__[modId].m; m._exports = m._tempexports; var desp = Object.getOwnPropertyDescriptor(m, "exports"); if (desp && desp.configurable) Object.defineProperty(m, "exports", { set: function (val) { if(typeof val === "object" && val !== m._exports) { m._exports.__proto__ = val.__proto__; Object.keys(val).forEach(function (k) { m._exports[k] = val[k]; }); } m._tempexports = val }, get: function () { return m._tempexports; } }); __MODS__[modId].status = 1; __MODS__[modId].func(__MODS__[modId].req, m, m.exports); } return __MODS__[modId].m.exports; };
var __REQUIRE_WILDCARD__ = function(obj) { if(obj && obj.__esModule) { return obj; } else { var newObj = {}; if(obj != null) { for(var k in obj) { if (Object.prototype.hasOwnProperty.call(obj, k)) newObj[k] = obj[k]; } } newObj.default = obj; return newObj; } };
var __REQUIRE_DEFAULT__ = function(obj) { return obj && obj.__esModule ? obj.default : obj; };
__DEFINE__(1720447972763, function(require, module, exports) {
var __TEMP__ = require('@hw-agconnect/core');var t = __TEMP__['DEFAULT_CATEGORY'];var __TEMP__ = require('@hw-agconnect/api');var n = __REQUIRE_DEFAULT__(__TEMP__);var e=function(){function t(t){this.encryptImpl=void 0,this.encryptImpl=t}return t.prototype.setEncryptImp=function(t){this.encryptImpl=t},t.prototype.decrypt=function(t){return null!=this.encryptImpl&&null!=this.encryptImpl&&null!=t&&null!=t?this.encryptImpl.decrypt(t):t},t.prototype.encrypt=function(t){return null!=this.encryptImpl&&null!=this.encryptImpl&&null!=t&&null!=t?this.encryptImpl.encrypt(t):t},t}(),r=function(){function t(){this.agcCryptImpl=new e}return t.getInstance=function(n,e){t.MiniProgramStorageMap.has(n)&&t.MiniProgramStorageMap.get(n)||t.MiniProgramStorageMap.set(n,new t);var r=t.MiniProgramStorageMap.get(n);return r.agcCryptImpl.setEncryptImp(e),r},t.prototype.get=function(t){var n=this;return new Promise((function(e,r){try{wx.getStorage({key:t,success:function(t){e(t?n.agcCryptImpl.decrypt(t.data):void 0)},fail:function(t){e(void 0)}})}catch(t){r(t)}}))},t.prototype.set=function(t,n){var e=this;return new Promise((function(r,o){try{wx.setStorage({key:t,data:e.agcCryptImpl.encrypt(n),success:function(){r()},fail:function(t){o(t)}})}catch(t){o(t)}}))},t.prototype.remove=function(t){return new Promise((function(n,e){try{wx.removeStorage({key:t,success:function(){n()},fail:function(t){e(t)}})}catch(t){e(t)}}))},t.MiniProgramStorageMap=new Map,t}(),o=function(){function n(n){this.name=t,n&&(this.name=n)}return n.prototype.getStorageInstance=function(t,n){return r.getInstance(this.name,n)},n.prototype.createPersistentStorage=function(){return r.getInstance(this.name)},n.prototype.createTemporaryStorage=function(){return r.getInstance(this.name)},n.prototype.createMemoryStorage=function(){return r.getInstance(this.name)},n}();n.registerInternalService({name:"AGCStorageService",serviceFactory:function(t){return new o(t.name())}});if (!exports.__esModule) Object.defineProperty(exports, "__esModule", { value: true });Object.defineProperty(exports, 'WxFactoryImpl', { enumerable: true, configurable: true, get: function() { return o; } });

}, function(modId) {var map = {}; return __REQUIRE__(map[modId], modId); })
return __REQUIRE__(1720447972763);
})()
//miniprogram-npm-outsideDeps=["@hw-agconnect/core","@hw-agconnect/api"]
//# sourceMappingURL=index.js.map